# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mitchell Spryn
email: mitchell.spryn@gmail.com
name: MitchellSpryn
description: > # this means to ignore newlines until "baseurl:"
  A place for technical tutorials, project summaries, and rants and raves about robotics, machine learning, and cloud computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mitchellspryn.com"
repository: "BlogRaw"
staticman_branch: "master"
github_username:  mitchellspryn

#for social
social:
  github: "mitchellspryn"
  linkedin: "mitchell-spryn-57834545"

collections:
  comments:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
#theme: minima
theme: jekyll-clean-dark
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

